config/routes.rb
Rails.application.routes.draw do
  constraints Clearance::Constraints::SignedIn.new do
    # user sent to dashboards controller if signed in
    root to: "dashboards#show", as: :dashboards_root
  end
  root to: "homes#show", as: :homes_root
  resources :shouts, only: [:create, :show]
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, only: [:create]

  resources :users, only: [:create, :show] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  def email
    ""
  end
end

app/models/shout.rb
class Shout < ApplicationRecord
  belongs_to :user
  belongs_to :content, polymorphic: true
  validates :user, presence: true

  default_scope { order(created_at: :desc) }

  # provides additional meaning. username comes from user, so we can call it on shouts
  delegate :username, to: :user
end

app/models/text_shout.rb
class TextShout < ApplicationRecord
  validates :body, presence: true, length: { in: 1..144 }
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  validates :username, presence: true, uniqueness: true
  has_many :shouts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @shout = Shout.new
    @shouts = current_user.shouts
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # before_action :redirect_to_dashboard_if_signed_in
  def show
    render
  end

  # private

  # def redirect_to_dashboard_if_signed_in
  #   if signed_in?
  #     redirect_to dashboard_path
  #   end
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  private

  def authenticate(_)
    super(session_params)
  end

  def session_params
    { session: session_params_with_email }
  end

  def session_params_with_email
    params.
      require(:session).
      permit(:password).
      # won't fail if no user
      merge(email: user.email)
  end

  def user
    # Using a where will return a relation. We want the first result. Either returns user we found or a guest object
    User.where(email: email_or_username).or(User.where(username: email_or_username)).first || Guest.new
  end

  def email_or_username
    params[:session][:email_or_username]
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def show
    @shout = Shout.find(params[:id])
  end


  def create
    # to persist our shouts
    shout = current_user.shouts.create(shout_params)
    # message if shout is not successful
    redirect_to homes_root_path, redirect_options_for(shout)
  end

  def shout_params
    { content: content_from_params }
  end

  def content_from_params
    TextShout.new(content_params)
  end

  def content_params
    params.require(:shout).require(:content).permit(:body)
  end

  def redirect_options_for(shout)
    if shout.persisted?
      { notice: "Shouted!" }
    else
      { alert: "Could not shout" }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def new
    @user = User.new
    render template: "users/new"
  end

  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     redirect_to '/'
  #   end
  # end

  def show
    @user = User.find(params[:id])
    @shouts = @user.shouts
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shouts_helper.rb
module ShoutsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/show.html.erb
<h1>Dashboard</h1>

<%= form_for @shout do |f| %>
  <%= f.fields_for :content do |content_form| %>
    <%= content_form.text_field :body, placeholder: "shout here!", required: true %>
  <% end %>
  <%= f.submit "Submit" %>
<% end %>

<%= render @shouts %>

app/views/homes/show.html.erb
<h1>Shoutr</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoutr</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= link_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

    <%= yield %>
  </body>

</html>

app/views/shouts/_shout.html.erb
<!-- Partial -->
<div>
  <%= link_to shout.user.username, shout.user %>
  <%= shout.content.body %>
  <%= link_to shout do %>
    <%= time_ago_in_words(shout.created_at) %> ago
  <% end %>
</div>

app/views/shouts/show.html.erb
<%= render @shout %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.email_field :email %>
</div>

<div class="text-field">
  <%= form.label :username %>
  <%= form.text_field :username %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<%= render @shouts %>